# Generated by Django 5.1.7 on 2025-03-13 08:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('idRole', models.IntegerField(primary_key=True, serialize=False)),
                ('nameRole', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('idUserType', models.IntegerField(primary_key=True, serialize=False)),
                ('nameUserType', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('profilePicture', models.ImageField(null=True, upload_to='')),
                ('phone', models.IntegerField()),
                ('userType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.usertype')),
            ],
        ),
        migrations.CreateModel(
            name='BussinessAccount',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='account.account')),
                ('nitBussinessAccount', models.IntegerField(blank=True)),
                ('nameBussiness', models.CharField(max_length=20)),
                ('roleBussinessAccount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.role')),
            ],
        ),
        migrations.CreateModel(
            name='PersonAccount',
            fields=[
                ('associatedAccount', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='account.account')),
                ('firstName', models.CharField(max_length=30)),
                ('lastName', models.CharField(max_length=30)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.role')),
            ],
        ),
    ]
