# Generated by Django 5.1.6 on 2025-05-13 07:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="account",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "profilePicture",
                    models.ImageField(blank=True, null=True, upload_to=""),
                ),
                ("rating", models.FloatField(default=0)),
                ("rating_count", models.IntegerField(default=0)),
                ("phone", models.IntegerField()),
                ("creationDate", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                ("idRole", models.IntegerField(primary_key=True, serialize=False)),
                ("nameRole", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="UserType",
            fields=[
                ("idUserType", models.IntegerField(primary_key=True, serialize=False)),
                ("nameUserType", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="BussinessAccount",
            fields=[
                (
                    "associatedAccount",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="bussinessAccount",
                        serialize=False,
                        to="account.account",
                    ),
                ),
                ("nitBussinessAccount", models.IntegerField(blank=True)),
                ("nameBussiness", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="PersonAccount",
            fields=[
                (
                    "associatedAccount",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="personAccount",
                        serialize=False,
                        to="account.account",
                    ),
                ),
                ("firstName", models.CharField(max_length=30)),
                ("lastName", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "receiver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_messages",
                        to="account.account",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_messages",
                        to="account.account",
                    ),
                ),
            ],
            options={
                "ordering": ["timestamp"],
            },
        ),
        migrations.AddField(
            model_name="account",
            name="role",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="account.role"
            ),
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateTimeField(auto_now_add=True)),
                ("type", models.CharField(max_length=7)),
                ("is_active", models.BooleanField(default=False)),
                (
                    "belongs_to",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscription",
                        to="account.account",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="account",
            name="userType",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="account.usertype"
            ),
        ),
    ]
