# Generated by Django 5.1.7 on 2025-03-13 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaccount',
            name='role',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.role'),
        ),
    ]
