# Generated by Django 5.1.7 on 2025-03-13 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_personaccount_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bussinessaccount',
            old_name='id',
            new_name='associatedAccount',
        ),
    ]
