# Generated by Django 5.1.7 on 2025-03-15 23:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_rename_id_bussinessaccount_associatedaccount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bussinessaccount',
            name='roleBussinessAccount',
        ),
        migrations.RemoveField(
            model_name='personaccount',
            name='role',
        ),
        migrations.AddField(
            model_name='account',
            name='role',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='account.role'),
            preserve_default=False,
        ),
    ]
