# Generated by Django 5.1.7 on 2025-03-20 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_account_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='profilePicture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
