# Generated by Django 5.1.7 on 2025-04-16 10:01

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_account_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='rating',
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField(help_text='Rating must be between 1 and 5.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('fromUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to', to='account.account')),
                ('originUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origin', to='account.account')),
            ],
        ),
    ]
