# Generated by Django 5.1.7 on 2025-04-16 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_remove_account_rating_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='rating',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
