# Generated by Django 5.1.7 on 2025-04-17 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_account_rating_delete_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='rating_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bussinessaccount',
            name='associatedAccount',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='bussinessAccount', serialize=False, to='account.account'),
        ),
        migrations.AlterField(
            model_name='personaccount',
            name='associatedAccount',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='personAccount', serialize=False, to='account.account'),
        ),
    ]
