# Generated by Django 5.1.7 on 2025-04-18 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_account_rating_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='rating',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='account',
            name='rating_count',
            field=models.IntegerField(default=0),
        ),
    ]
