# Generated by Django 5.1.7 on 2025-03-13 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cardinality',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RoadType',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.city')),
            ],
        ),
        migrations.CreateModel(
            name='Neighborhood',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('dID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.district')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('road', models.IntegerField()),
                ('roadPrefix', models.CharField(blank=True, max_length=10, null=True)),
                ('crossingPrefix', models.CharField(blank=True, max_length=10, null=True)),
                ('crossingCardinality', models.CharField(blank=True, max_length=10, null=True)),
                ('plateNumber', models.CharField(max_length=10)),
                ('roadCardinality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='property.cardinality')),
                ('neigID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.neighborhood')),
                ('roadType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.roadtype')),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=1000)),
                ('image', models.ImageField(null=True, upload_to='property/images')),
                ('propertyType', models.CharField(max_length=20)),
                ('price', models.FloatField()),
                ('location', models.URLField()),
                ('socioEconomicStatus', models.CharField(max_length=1)),
                ('addressID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='property.address')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='provinID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.province'),
        ),
    ]
