# Generated by Django 5.1.6 on 2025-05-15 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("property", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visit",
            name="date",
            field=models.DateTimeField(),
        ),
    ]
