# Generated by Django 5.1.6 on 2025-05-15 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("property", "0002_alter_visit_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visit",
            name="date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
