# Generated by Django 5.1.7 on 2025-03-14 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_propertytype_remove_property_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='socioEconomicStatus',
            new_name='SES',
        ),
    ]
