# Generated by Django 5.1.6 on 2025-05-15 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("property", "0003_alter_visit_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointmentstatus",
            name="name",
            field=models.CharField(max_length=30),
        ),
    ]
