# Generated by Django 5.1.6 on 2025-02-19 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_city_province_alter_property_description_district_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='property.district'),
        ),
    ]
