# Generated by Django 5.1.6 on 2025-02-19 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_property_district'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='district',
        ),
        migrations.AlterField(
            model_name='property',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='property',
            name='identificator',
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name='Neighborhood',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('dID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.district')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roadType', models.CharField(max_length=50)),
                ('road', models.IntegerField()),
                ('roadPrefix', models.CharField(blank=True, max_length=10, null=True)),
                ('crossingPrefix', models.CharField(blank=True, max_length=10, null=True)),
                ('roadCardinality', models.CharField(blank=True, max_length=10, null=True)),
                ('crossingCardinality', models.CharField(blank=True, max_length=10, null=True)),
                ('plateNumber', models.CharField(max_length=10)),
                ('neigID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.neighborhood')),
            ],
        ),
    ]
