# Generated by Django 5.1.6 on 2025-02-19 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_remove_property_district_alter_property_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='identificator',
        ),
    ]
