# Generated by Django 5.1.6 on 2025-02-20 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0006_remove_property_identificator'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cardinality',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='RoadType',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='property',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='property.address'),
        ),
        migrations.AlterField(
            model_name='address',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='address',
            name='roadCardinality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.cardinality'),
        ),
        migrations.AlterField(
            model_name='address',
            name='roadType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.roadtype'),
        ),
    ]
