# Generated by Django 5.1.6 on 2025-02-20 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_cardinality_roadtype_property_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='address',
        ),
        migrations.AddField(
            model_name='property',
            name='addressID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='address', to='property.address'),
        ),
        migrations.AlterField(
            model_name='address',
            name='neigID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='neighborhood', to='property.neighborhood'),
        ),
        migrations.AlterField(
            model_name='neighborhood',
            name='dID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='district', to='property.district'),
        ),
    ]
