# Generated by Django 5.1.7 on 2025-03-15 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_alter_propertytype_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='addressID',
        ),
    ]
