# Generated by Django 5.1.6 on 2025-02-20 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_remove_property_address_property_addressid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='neigID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.neighborhood'),
        ),
        migrations.AlterField(
            model_name='address',
            name='roadCardinality',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='property.cardinality'),
        ),
        migrations.AlterField(
            model_name='neighborhood',
            name='dID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.district'),
        ),
        migrations.AlterField(
            model_name='property',
            name='addressID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='property.address'),
        ),
    ]
