# Generated by Django 5.1.6 on 2025-02-20 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0009_alter_address_neigid_alter_address_roadcardinality_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='roadCardinality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='property.cardinality'),
        ),
    ]
