# Generated by Django 5.1.7 on 2025-03-16 00:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_remove_bussinessaccount_rolebussinessaccount_and_more'),
        ('property', '0010_remove_city_provinid_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='associatedAccount',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='account.account'),
            preserve_default=False,
        ),
    ]
