# Generated by Django 5.1.7 on 2025-03-16 01:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_remove_bussinessaccount_rolebussinessaccount_and_more'),
        ('property', '0011_property_associatedaccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favourites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('associatedAccount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.account')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.property')),
            ],
            options={
                'unique_together': {('associatedAccount', 'property')},
            },
        ),
    ]
