# Generated by Django 5.1.7 on 2025-03-20 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_account_user'),
        ('property', '0012_favourites'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coordinates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='address',
            name='neigID',
        ),
        migrations.RemoveField(
            model_name='address',
            name='roadCardinality',
        ),
        migrations.RemoveField(
            model_name='address',
            name='roadType',
        ),
        migrations.RemoveField(
            model_name='neighborhood',
            name='dID',
        ),
        migrations.AlterField(
            model_name='favourites',
            name='associatedAccount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favouriteAccs', to='account.account'),
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coordinates', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.coordinates')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.district')),
            ],
        ),
        migrations.AddField(
            model_name='property',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='property.location'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Cardinality',
        ),
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.DeleteModel(
            name='RoadType',
        ),
        migrations.DeleteModel(
            name='Neighborhood',
        ),
    ]
