# Generated by Django 5.1.7 on 2025-03-20 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0013_coordinates_remove_address_neigid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='location',
        ),
    ]
