# Generated by Django 5.1.7 on 2025-03-20 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0014_remove_property_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='property.location'),
            preserve_default=False,
        ),
    ]
