# Generated by Django 5.1.7 on 2025-03-20 11:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0015_property_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='creationDate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
