# Generated by Django 5.1.7 on 2025-04-16 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_account_rating_delete_rating'),
        ('property', '0017_alter_property_associatedaccount_visit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='visited_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='account.account'),
        ),
    ]
