# Generated by Django 5.1.7 on 2025-04-16 12:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0018_alter_visit_visited_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
