# Generated by Django 5.1.7 on 2025-04-17 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_account_rating_delete_rating'),
        ('property', '0021_alter_visit_date_reviews'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reviews',
            new_name='Review',
        ),
    ]
