# Generated by Django 5.1.7 on 2025-04-17 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0022_rename_reviews_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='rate',
            new_name='rating',
        ),
    ]
