# Generated by Django 5.1.7 on 2025-04-18 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0023_rename_rate_review_rating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
