# Generated by Django 5.1.7 on 2025-04-18 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_account_rating_count_and_more'),
        ('property', '0024_delete_appointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.property')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.account')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.appointmenttype')),
            ],
        ),
    ]
