# Generated by Django 5.1.7 on 2025-04-18 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0025_appointmenttype_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='property.property'),
        ),
    ]
