# Generated by Django 5.1.7 on 2025-04-18 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0026_alter_appointment_property'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AppointmentType',
            new_name='AppointmentStatus',
        ),
    ]
