# Generated by Django 5.1.7 on 2025-04-18 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0027_rename_appointmenttype_appointmentstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='property.appointmentstatus'),
        ),
    ]
