# Generated by Django 5.1.7 on 2025-05-11 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0028_alter_appointment_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Province',
        ),
    ]
